### ISSUE TITLE
Deal With Spaces When Converting

### ISSUE THREAD

**Issue by KaspianDev** [supsm/MCPPPP#22] opened 2022-03-18 20:05 UTC
**Describe the bug**
When convering in pack that has spaces in folder names, minecraft crashes, because converter errors during convertion.

**Screenshots**

**Important stuff**
- OS: Windows
- Version/Commit Number: 0.6.1

**Resourcepack**
https://www.curseforge.com/minecraft/texture-packs/bettervanillabuilding

**Logs**
```
[20:56:18] Error: tried to copy nonexistent file
mcpppp-temp/BetterVanillaBuildingV2.71/assets/minecraft/textures/optifine/cit/items/christmas/string lights/tree/yellowtree.png
[20:56:18] Error: tried to copy nonexistent file
mcpppp-temp/BetterVanillaBuildingV2.71/assets/minecraft/textures/optifine/cit/items/christmas/string lights/tree/yellowtree.png
```

**Comment by supsm** [comment] 2022-03-18 20:22
Can you send full logs? It may be more useful

**Comment by supsm** [comment] 2022-03-19 22:33
Note to self: the crash is actually caused by an assertion in reselect's add_random. It doesn't show up in the logs however, since assertions are only outputted to standard output. I'll try to see if I can get around this somehow

**Comment by supsm** [comment] 2022-03-21 05:46
The crash should be fixed in the latest commit

**Comment by KaspianDev** [comment] 2022-03-21 12:19
Same result

**Comment by supsm** [comment] 2022-05-18 20:36
Should be fixed in 0.7.0, sorry for the late notice

**Closed by supsm** 2022-05-18 20:36 UTC
Labels: bug, working on
