### ISSUE TITLE
Crashes 

### ISSUE THREAD

**Issue by Aces-and-Jacks** [supsm/MCPPPP#30] opened 2022-09-13 19:00 UTC
**Describe the bug**
Launched my game with the mod and it crashed

**Screenshots**

**Important stuff**
- OS: [Mac]
- Version/Commit Number: 0.7.3

**Resourcepack**
none

**Logs**
[[Upload logs](https://mclo.gs/R8GxjVV)]

**Additional context**

**Comment by supsm** [comment] 2022-09-13 20:37
Hmm, mac compat has some issues ad I'm not sure if it'll work on arm. What version of macOS are you running?
In the meantime, you could try the standalone converter (download in [releases](https://github.com/supsm/MCPPPP/releases/latest)) or [web converter](https://supsm.github.io/MCPPPP)

**Comment by Aces-and-Jacks** [comment] 2022-09-13 21:45
I'm running macOS 12.4

**Comment by Aces-and-Jacks** [comment] 2022-09-14 03:22
It's not the latest OS but I don't have a way to back up my computer and don't want to lose anything

**Comment by supsm** [comment] 2022-09-14 03:23
You don't need to update, that version should be fine. If yo could try the cli or GUI standalone converter (from the releases), it might provide more debug info for me.

**Comment by Aces-and-Jacks** [comment] 2022-09-14 03:30
Would I just convert it to a jar file?

**Comment by supsm** [comment] 2022-09-14 03:30
No, run it like other applications (double click in finder or run from a terminal window), there should be instructions somewhere as well.

**Comment by Aces-and-Jacks** [comment] 2022-09-14 03:31
So I run the executable

**Comment by Aces-and-Jacks** [comment] 2022-09-14 03:36
<img width="789" alt="Screen Shot 2022-09-13 at 11 34 20 PM" src="https://user-images.githubusercontent.com/106651342/190053864-54c9a401-7788-4d7b-8e5f-6bd418624194.png">

**Comment by Aces-and-Jacks** [comment] 2022-09-14 03:36
?

**Comment by supsm** [comment] 2022-09-14 03:40
Hmm that looks fine (you need to specify which resource packs to convert in the command-line or config file in the cli version, use the --help flag or GUI version if cli is too difficult), it's probably something to do with my mod "wrapper". I'll see what I can do, but don't expect it to be done soon as I am busy.

**Comment by supsm** [comment] 2022-09-14 03:42
actually, this looks like a duplicate of #27. If you need assistance with standalone/web converter, please ask in the [discord server](https://discord.gg/waXJDswsaR)

**Closed by supsm** 2022-09-14 03:42 UTC
Labels: bug, mod
